### ISSUE TITLE
Why is it so unintuitive to specify custom commands? 

### ISSUE THREAD

**Issue by nush-1qb** [gocd-demo/sample-k8s-workflow#1]
I am looking at the example for how to build and publish a docker image, and the command that actually works is like this:

```
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application
                command: /bin/bash
                run_if: passed
```

This seems like such a round-about way of calling docker build. The existing docker build command that is provided by the default command repo is broken too. 

What's up with that?
